spring:
  application:
    name: ${APPLICATION_NAME:notification-service}

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      group-id: ${KAFKA_CONSUMER_GROUP_ID:services-group}

    custom:
      enable-listeners: ${KAFKA_ENABLE_LISTENERS:true}
#      notification-service-topic: ${KAFKA_NOTIFICATION_TOPIC:notification-service-events}
      tutor-signup-topic: ${KAFKA_TUTOR_SIGNUP_TOPIC:tutor-signup-events}
      student-signup-topic: ${KAFKA_STUDENT_SIGNUP_TOPIC:student-signup-events}
      student-detail-after-reservation-email-topic: ${KAFKA_STUDENT_DETAIL_RESERVATION_TOPIC:student-detail-after-reservation-email-events}
      reservation-approved-email-topic: ${KAFKA_RESERVATION_APPROVED_EMAIL_TOPIC:reservation-approved-email-events}

  sleuth:
    enabled: ${SLEUTH_ENABLED:true}
    sampler:
      probability: 1

  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    base-url: ${ZIPKIN_URL:http://localhost:9411/}

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
    username: krv.marketplace@gmail.com
    password: awtbgtcwdcbxcjvj
    properties:
      mail:
        smtp:
          starttls:
              enable: true
              starttls:
                required: true
          auth: true
server:
  port: ${SERVER_PORT:8086}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

#Email Configuration
#spring:
#    mail:
#      host: smtp.gmail.com
#      port: 587
#      protocol: smtp
#      default-encoding: UTF-8
#      username: verapmiu2022@gmail.com
#      password: pezlsezajkbtejwn
#      properties:
#          mail:
#            smtp:
#               starttls:
#                 enable: true
#                 starttls:
#                   required: true
#                 auth: true
#    spring.mail.host = smtp.gmail.com
#    spring.mail.port = 587
#    spring.mail.protocol=smtp
#    spring.mail.default-encoding=UTF-8
#    spring.mail.username=verapmiu2022@gmail.com
#    spring.mail.password=pezlsezajkbtejwn
#    spring.mail.properties.mail.smtp.starttls.enable=true
#    spring.mail.properties.mail.smtp.starttls.required=true
#    spring.mail.properties.mail.smtp.auth=true