spring:
  application:
    name: authentication-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:swa}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: ${KAFKA_CONSUMER_GROUP_ID:services-group}
    custom:
      enable-listeners: ${KAFKA_ENABLE_LISTENERS:true}
      tutor-signup-topic: ${KAFKA_TUTOR_SIGNUP_TOPIC:tutor-signup-events}
      student-signup-topic: ${KAFKA_STUDENT_SIGNUP_TOPIC:student-signup-events}
      reservation-topic: ${KAFKA_RESERVATION_TOPIC:reservation-events}
      student-detail-after-reservation-email-topic: ${KAFKA_STUDENT_DETAIL_RESERVATION_TOPIC:student-detail-after-reservation-email-events}
      reservation-approved-topic: ${KAFKA_RESERVATION_APPROVED_TOPIC:reservation-approved-events}
      reservation-approved-email-topic: ${KAFKA_RESERVATION_APPROVED_EMAIL_TOPIC:reservation-approved-email-events}

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080

app:
  security:
    jwt:
      secret: secret
      expiry: 100000

